const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    userId: { type: String, required: true, unique: true },
    email: { type: String, default: '' },
    displayName: { type: String, default: '' },
    photoUrl: { type: String, default: '' },
    mobileNo: { type: String, default: '' },
    gender: { type: String, default: 'Male' },
    coins: { type: Number, default: 0 },
    bonusCoins: { type: Number, default: 0 },
    totalCoins: { type: Number, default: 0 },
    gems: { type: Number, default: 0 },
    referralCode: { type: String, required: true, unique: true },
    referredBy: { type: String, default: '' },
    upline: [{ type: String }],
    referred: { type: Boolean, default: false },
    referrerBonusClaimed: { type: Boolean, default: false },
    ipAddress: { type: String, default: '' },
    countryCode: { type: String, default: 'IN' },
    deviceId: { type: String, default: '' },
    physicalDeviceId: { type: String, default: '' },
    isRooted: { type: Boolean, default: false },
    isEmulator: { type: Boolean, default: false },
    isVpnActive: { type: Boolean, default: false },
    isDeveloperOptions: { type: Boolean, default: false },
    isMockLocation: { type: Boolean, default: false },
    gaid: { type: String, default: '' },
    isGuest: { type: Boolean, default: false },
    account_deleted: { type: Boolean, default: false },
    account_deleted_at: { type: Date, default: null },
    delete_requested: { type: Boolean, default: false },
    delete_requested_at: { type: Date, default: null },
    isBlocked: { type: Boolean, default: false },
    isLeaderboardBanned: { type: Boolean, default: false },
    payoutBlocked: { type: Boolean, default: false },
    payoutBlockReason: { type: String, default: '' },
    payoutBlockUpdatedAt: { type: Date, default: null },
    isAnonymous: { type: Boolean, default: false },
    streak: { type: Number, default: 1 },
    streakClaimed: { type: Boolean, default: false },
    lastStreakDateStr: { type: String, default: '' },
    socialFollowed: [{ type: String }],
    source: { type: String, default: '' },
    publisherRef: { type: String, default: '' },
    publisherUid: { type: String, default: '' },
    firstLogin: { type: Date, default: Date.now },
    lastActiveAt: { type: Date, default: Date.now },
    superOfferAssignType: { type: String, default: 'hours' },
    superOfferLimit: { type: Number },
    superOfferReward: { type: Number, default: 100 },
    superOfferGemsRequired: { type: Number, default: 10 },
    superOfferAdsRequired: { type: Boolean, default: true },
    superOfferInstallTask: { type: Boolean, default: true },
    superOfferDailyGemsForInstall: { type: Number, default: 2 },
    superOfferGameGems: { type: Number, default: 1 },
    superOfferInstallGems: { type: Number, default: 5 },
    superOfferAssignedAt: { type: Date, default: null },
    superOfferAssignedDateStr: { type: String, default: '' },
    superOfferGameInstallTriggerAt: { type: Number, default: 2 },
    superOfferGapMinutes: { type: Number, default: null },
    superOfferClaimsToday: { type: Number, default: 0 },
    superOfferClaimsDateStr: { type: String, default: '' },
    isSuperOfferUnlocked: { type: Boolean, default: false },
    superOfferUnlockedAt: { type: Date, default: null },
    gameDailyLimit: { type: Number },
    gameClaimsToday: { type: Number, default: 0 },
    gameAssignedAt: { type: Date, default: null },
    gameAssignedDateStr: { type: String, default: '' },
    battleInstallTaskNumber: { type: Number, default: 0 },
    battleInstallTaskCompletedToday: { type: Boolean, default: false },
    battleInstallTaskAssignedDate: { type: Date, default: null },
    battleInstallTaskAssignedDateStr: { type: String, default: '' },
    freeBattlesJoinedToday: { type: Number, default: 0 },
    battleDailyLimit: { type: Number, default: -1 },
    battlesJoinedToday: { type: Number, default: 0 },
    clientPublicKey: { type: String, default: '' },
    clientPrivateKeyEncrypted: { type: String, default: '' },
    claimedReferralMissions: [{ type: String }],
    createdAt: { type: Date, default: Date.now }
}, { timestamps: true });

userSchema.index({ userId: 1 });
userSchema.index({ referralCode: 1 });
userSchema.index({ referredBy: 1 });

module.exports = mongoose.model('User', userSchema);
